"""Shared BPMN 2.0 parser. Parses full BPMN, classifies each element by executability tier
(ADR-027: executable / documented / unknown), and reports the executable subset + topology the
registry validates and the agent-runtime compiles."""
from amendia_bpmn.model import (
    DEFAULT_CALL_VERSION_RANGE,
    EXTENDED_TASK_KINDS,
    TASK_EXECUTOR_CATEGORY,
    TASK_KINDS,
    BoundaryTimer,
    BpmnModel,
    CallActivity,
    ClassifiedElement,
    ErrorBoundary,
    Finding,
    Flow,
    MultiInstance,
    SubProcess,
    TimerDef,
    compute_sha256,
    local_name,
)
from amendia_bpmn.compilability import (
    COMMON_EXECUTABLE,
    COMMON_SUBSET,
    EXECUTION_PROFILES,
    compilability_findings,
    normalize_profile,
    profile_rank,
    required_profile,
)
from amendia_bpmn.dmn import (
    DecisionEvaluationError,
    DecisionTable,
    DmnError,
    evaluate as evaluate_decision,
    parse_decision_table,
    validate_table,
)
from amendia_bpmn.reduce import (
    ReduceConfig,
    ReduceError,
    ReduceEvaluationError,
    evaluate_reduce,
    parse_reduce_config,
    validate_reduce,
)
from amendia_bpmn.parser import parse, select_process_id
from amendia_bpmn.semantics import BpmnSemanticModel, extract_semantics
from amendia_bpmn.timers import UnsupportedTimer, parse_iso_duration, parse_timer, timer_is_supported

__all__ = [
    "BoundaryTimer",
    "BpmnModel",
    "BpmnSemanticModel",
    "ClassifiedElement",
    "ErrorBoundary",
    "EXECUTION_PROFILES",
    "COMMON_EXECUTABLE",
    "COMMON_SUBSET",
    "EXTENDED_TASK_KINDS",
    "CallActivity",
    "DEFAULT_CALL_VERSION_RANGE",
    "Finding",
    "Flow",
    "MultiInstance",
    "SubProcess",
    "TASK_EXECUTOR_CATEGORY",
    "TASK_KINDS",
    "TimerDef",
    "UnsupportedTimer",
    "DecisionEvaluationError",
    "DecisionTable",
    "DmnError",
    "evaluate_decision",
    "parse_decision_table",
    "validate_table",
    "ReduceConfig",
    "ReduceError",
    "ReduceEvaluationError",
    "evaluate_reduce",
    "parse_reduce_config",
    "validate_reduce",
    "compilability_findings",
    "compute_sha256",
    "extract_semantics",
    "local_name",
    "normalize_profile",
    "parse",
    "parse_iso_duration",
    "parse_timer",
    "profile_rank",
    "required_profile",
    "select_process_id",
    "timer_is_supported",
]
